services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kararai-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/kararai.db
      - SECRET_KEY=your-super-secret-key-change-in-production-docker
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://localhost:8080,https://your-vercel-domain.vercel.app
    volumes:
      - backend_data:/app/data
      - backend_logs:/app/logs
      - backend_temp:/app/temp
      # For development - comment out for production
      # - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
  backend_logs:
  backend_temp: